### PR TITLE
app-editors/sublime-text: Version bump; bump to EAPI=5

### PR DESCRIPTION
**Pull request by marbre**
Add 3080 and 3083. Replace EAPI=4 by EAPI=5.

Package-Manager: portage-2.2.14

### CODE REVIEW

**Comment by DamnWidget** [comment]
I can't merge this as the commit breaks the test suite.

**Comment by marbre** [comment]
Yes, I see... Actually I justed copied 3065 and only replaced the `EAPI`. But it might be necessary to define the keywords before they can be used as conditional arguments in the `SRC_URI`. I'll change that, commit and we'll see what travis says about it.

**Comment by marbre** [comment]
I justed checked some of the ebuilds I maintain for the science overlay. With `EAPI=5` it is okay to define `SRC_URI` before setting the `KEYWORDS` variable. Running `repoman -vdx full` in my fork of your overlay gives me no error. Maybe something with the travis configuration? This is slightly different for the science overlay, anyway I don't see the difference in the configs which might be the reason for a failing build...

**Comment by DamnWidget** [comment]
The `-d` option includes the dev profiles, I will prefer to don't do it, can you just use the current EAPI version?

**Comment by DamnWidget** [comment]
Hmmm, seems like the version of repoman that travis uses is old, so I am merging your commit now (it's a travis problem after all)

**Comment by DamnWidget** [comment]
Yes please, Travis is smashing me each while with emails about the failed
status of the build.

Pretty annoying

**Pull request merged**
