### PR TITLE
added version 3143

### PR DESCRIPTION
**Pull request by soltysek**
Ebuild for new version

### CODE REVIEW

**Comment by DamnWidget** [comment]
Thank you for your contribution.
Do you think you could fix the QA failures? https://travis-ci.org/DamnWidget/sublime-text/builds/275161739?utm_source=github_status&utm_medium=notification

**Comment by soltysek** [comment]
I'm new to writing ebuilds so probably I can't fix them by myself. Also I'm not able to reproduce those QA failures in my local system.

**Comment by soltysek** [comment]
I've fixed errors that `repoman -dx full` was showing on my machine

**Comment by soltysek** [comment]
In travis log there is also information 

>  !!! .travis.yml outdated! Update available https://github.com/mrueg/repoman-travis 

maybe it's somehow related to different errors on my box and travis

**Comment by daboross** [comment]
Hi!

I believe updating repoman-travis fixes the remaining errors. I've sent a pull request to this pull request branch at https://github.com/soltysek/sublime-text/pull/1 that passes travis.

I would have sent a pull request to this repository, but it seems that it won't succeed without the other changes already made here.

**Comment by DamnWidget** [comment]
Ok I will just accept this PR and update travis file myself.

Thank you again guys.

**Comment by daboross** [comment]
Thank you for maintaining this! 👍

**Pull request merged**
